version: "3.1"

services:
  db:
    image: postgres:15-bookworm
    container_name: db
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: kazee_employee_management

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    links:
      - db

volumes:
  dbdata:
